name: demo

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - runs-on: windows-latest
          compiler: gcc
        
    steps:
    - uses: actions/checkout@v2
    # - name: Set up MinGW
    #  uses: egor-tensin/setup-mingw@v2
    #  with:
    #    platform: x64
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade setuptools
        python3 -m pip install colorama lamden requests
    - name: Run demo
      run: |
        cd $GITHUB_WORKSPACE/
        python3 demo.py
