name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade setuptools
        python3 -m pip install pytest requests contracting flaky pytest-github-actions-annotate-failures pytest-cov pytest-repeat
    - name: Test with pytest
      run: |
        cd $GITHUB_WORKSPACE/contracts/
        python3 -m pytest tests/* --force-flaky --count=2 -v --cov=./ --cov-report=xml 
    # - name: Upload to codecov
    #  uses: codecov/codecov-action@v1
    #  with:
    #    file: contracts/coverage.xml
    #    flags: unittests
    #    env_vars: OS, PYTHON
